### ISSUE TITLE
E-hääletamiste jooksev nimekiri, electoralDistrictId -> electoralDistrictNr

### ISSUE THREAD

**Issue by toomy4** [e-gov/VIS3-EHS#12]
https://github.com/e-gov/VIS3-EHS/blob/31c49e67484d0db24568a33f1c9859dc8aeae61d/9_e_haaletamiste_jooksev_nimekiri/ehs-xroad-api.yaml#L177

Väja nimi electoralDistrictId ringkonna numbri väljendamiseks on vale. VIS3 jaoks ringkonna id on ringkonna primaarvõti üle kõigi valimissündmuste. Ringkonna number on ühe valimissündmuse (või KOV valimiste puhul ühe KOV-i) kontekstis ringkonna number. Need ei ole omavahel suvaliselt vahetatavad väärtused.

**Comment by PriitParmakson** [comment]
Sven, palun selgitame üle, mis meil electoralDistrictId all tuleb.
EHS saab valimisringkondade numbrid VIS3-st, liidese "Valimisringkondade nimekiri" kaudu. Seal valimisringkonna identifikaator saadetakse kujul eesliide.number.
Kas EHS peaks samal kujul tagasi saatma? Kas ja kus selle eesliite semantika on määratletud? Me ei saa muidugi tugineda VIS3 sisemuses olevatele stuktuuridele ega nõuetele, mida liidese spetsifikatsioonis pole eksponeeritud.

**Comment by PriitParmakson** [comment]
Arutelus selgus:
- KOV valimise korral määravad KOV kood ja ringkonnanumber ringkonna üheselt. Ringkonna number on ühene KOV sees. Nt:
```
kovCode: 0809
electoralDistrictId: 1
```
- RK, EP, EH korral pole KOV koodi vaja, ringkonna määrab üheselt number. Nt:
```
kovCode: 0624
electoralDistrictId: 12
```
Seetõttu valimissündmuse number on küll identifikaator, kuid KOV valimiste korral ainult piiratud skoobis (KOV piires). Muudame välja nime `Id` -> `No`.
