### ISSUE TITLE
E-hääletamiste jooksev nimekiri, YAML vs SPEC

### ISSUE THREAD

**Issue by 0lla** [e-gov/VIS3-EHS#13]
YAML ja spec failide erinevused. Nt: `electionname`vs `electionName` 

Valimise loetelu otspunkti vastuse erinevus
YAML:
`{
  "elections": [
    {
      "name": "RK_2023"
    }
  ]
}`
spec:
`[
  { "name": "RK_2023" }
]`

**Comment by toomy4** [comment]
Tõe allikaks lugeda yaml-it. See on tehniline spetsifikatsioon, mille peale integratsioon üles ehitada mõlemal pool. 

Muu dokumentatsioon vajab järgi aitamist

**Comment by PriitParmakson** [comment]
Viisin näite vastavusse OpenAPI-spetsifikatsiooniga.
